project:
  type: website
  output-dir: /Users/nathanheuver/Library/CloudStorage/OneDrive-UBC/Desktop/School/FCOR_599/eportfolio/E-Portfolio

website:
  title: "Nathan Heuver's E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: samplework.qmd
        text: Sample Work
      - href: pics.qmd
        text: Photo Resume


format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

